version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:management
    ports:
      - "5672:5672"
      - "15672:15672"

  servidor:
    build: .
    command: python servidor.py
    depends_on:
      - rabbitmq
    ports:
      - "8888:8888"

  worker1:
    build: .
    command: python workey.py worker1
    depends_on:
      - rabbitmq

  worker2:
    build: .
    command: python workey.py worker2
    depends_on:
      - rabbitmq